#!/bin/sh -l
#$ -S /bin/sh

echo "Adding Repositories and ppa";
sudo add-apt-repository ppa:webupd8team/sublime-text-3;

echo "Updating apt-get";
sudo apt-get update;

echo "Installing zsh and oh-my-zsh";
sudo apt-get install zsh;
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)";
chsh -s $(which zsh)

if [[ $(getconf LONG_BIT) = "64" ]]
then
    echo "64bit Detected" &&
    echo "Installing Google Chrome" &&
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
    sudo dpkg -i google-chrome-stable_current_amd64.deb &&
    rm -f google-chrome-stable_current_amd64.deb
else
    echo "32bit Detected" &&
    echo "Installing Google Chrome" &&
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb &&
    sudo dpkg -i google-chrome-stable_current_i386.deb &&
    rm -f google-chrome-stable_current_i386.deb
fi

echo "Installing Sublime Text 3";
sudo apt-get install sublime-text-installer;

echo "Installing virtualenv and virtualenvwrapper"
pip3 install virtualenv
mkdir ~/.virtualenvs
pip3 install virtualenvwrapper

echo "Installing 'thefuck'"
sudo apt install python3-dev python3-pip
pip3 install thefuck

echo "Making Projects directory"
mkdir ~/Projects

